/*
 * This file is generated by jOOQ.
 */
package com.rpkit.chat.bukkit.database.jooq.tables.records;


import com.rpkit.chat.bukkit.database.jooq.tables.RpkitChatNameColor;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is usually generated by jOOQ, but this file was copied and modified from another generated file.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitChatNameColorRecord extends TableRecordImpl<RpkitChatNameColorRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>rpkit_chat.rpkit_chat_name_color.minecraft_profile_id</code>.
     */
    public void setMinecraftProfileId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>rpkit_chat.rpkit_chat_name_color.minecraft_profile_id</code>.
     */
    public Integer getMinecraftProfileId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>rpkit_chat.rpkit_chat_name_color.chat_name_color</code>.
     */
    public void setChatNameColor(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>rpkit_chat.rpkit_chat_name_color.chat_name_color</code>.
     */
    public String getChatNameColor() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RpkitChatNameColor.RPKIT_CHAT_NAME_COLOR.MINECRAFT_PROFILE_ID;
    }

    @Override
    public Field<String> field2() {
        return RpkitChatNameColor.RPKIT_CHAT_NAME_COLOR.CHAT_NAME_COLOR;
    }

    @Override
    public Integer component1() {
        return getMinecraftProfileId();
    }

    @Override
    public String component2() {
        return getChatNameColor();
    }

    @Override
    public Integer value1() {
        return getMinecraftProfileId();
    }

    @Override
    public String value2() {
        return getChatNameColor();
    }

    @Override
    public RpkitChatNameColorRecord value1(Integer value) {
        setMinecraftProfileId(value);
        return this;
    }

    @Override
    public RpkitChatNameColorRecord value2(String value) {
        setChatNameColor(value);
        return this;
    }

    @Override
    public RpkitChatNameColorRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RpkitChatNameColorRecord
     */
    public RpkitChatNameColorRecord() {
        super(RpkitChatNameColor.RPKIT_CHAT_NAME_COLOR);
    }

    /**
     * Create a detached, initialised RpkitChatNameColorRecord
     */
    public RpkitChatNameColorRecord(Integer minecraftProfileId, String chatNameColor) {
        super(RpkitChatNameColor.RPKIT_CHAT_NAME_COLOR);

        setMinecraftProfileId(minecraftProfileId);
        setChatNameColor(chatNameColor);
    }
}