/*
 * This file is generated by jOOQ.
 */
package com.rpkit.chat.bukkit.database.jooq.tables;


import com.rpkit.chat.bukkit.database.jooq.RpkitChat;
import com.rpkit.chat.bukkit.database.jooq.tables.records.RpkitChatNameColorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is usually generated by jOOQ, but this file was copied and modified from another generated file.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RpkitChatNameColor extends TableImpl<RpkitChatNameColorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>rpkit_chat.rpkit_chat_name_color</code>
     */
    public static final RpkitChatNameColor RPKIT_CHAT_NAME_COLOR = new RpkitChatNameColor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RpkitChatNameColorRecord> getRecordType() {
        return RpkitChatNameColorRecord.class;
    }

    /**
     * The column
     * <code>rpkit_chat.rpkit_chat_name_color.minecraft_profile_id</code>.
     */
    public final TableField<RpkitChatNameColorRecord, Integer> MINECRAFT_PROFILE_ID = createField(DSL.name("minecraft_profile_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>rpkit_chat.rpkit_chat_name_color.chat_name_color</code>.
     */
    public final TableField<RpkitChatNameColorRecord, String> CHAT_NAME_COLOR = createField(DSL.name("chat_name_color"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    private RpkitChatNameColor(Name alias, Table<RpkitChatNameColorRecord> aliased) {
        this(alias, aliased, null);
    }

    private RpkitChatNameColor(Name alias, Table<RpkitChatNameColorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>rpkit_chat.rpkit_chat_name_color</code> table
     * reference
     */
    public RpkitChatNameColor(String alias) {
        this(DSL.name(alias), RPKIT_CHAT_NAME_COLOR);
    }

    /**
     * Create an aliased <code>rpkit_chat.rpkit_chat_name_color</code> table
     * reference
     */
    public RpkitChatNameColor(Name alias) {
        this(alias, RPKIT_CHAT_NAME_COLOR);
    }

    /**
     * Create a <code>rpkit_chat.rpkit_chat_name_color</code> table reference
     */
    public RpkitChatNameColor() {
        this(DSL.name("rpkit_chat_name_color"), null);
    }

    public <O extends Record> RpkitChatNameColor(Table<O> child, ForeignKey<O, RpkitChatNameColorRecord> key) {
        super(child, key, RPKIT_CHAT_NAME_COLOR);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : RpkitChat.RPKIT_CHAT;
    }

    @Override
    public RpkitChatNameColor as(String alias) {
        return new RpkitChatNameColor(DSL.name(alias), this);
    }

    @Override
    public RpkitChatNameColor as(Name alias) {
        return new RpkitChatNameColor(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitChatNameColor rename(String name) {
        return new RpkitChatNameColor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RpkitChatNameColor rename(Name name) {
        return new RpkitChatNameColor(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}